# Generated by roxytest: Do not edit by hand!

context("File R/add_abbrtable.R: @testexamples")

test_that("Function add_abbrtable() @ L19", {
  
  csvpath <- system.file("extdata", "myabbr.csv", package = "journalabbr", mustWork = TRUE)
  abbrtable_user <- add_abbrtable(file = csvpath, header = FALSE, sep = ";")
  colnames(abbrtable_user)
  
  expect_true(is.data.table(abbrtable_user))
})

