.onLoad <- function(...) {
  .tidytable_env <- new.env()
  tidytable_ns <- parent.env(environment())
  env_bind(tidytable_ns, .tidytable_env = .tidytable_env)
  dot_option <- getOption("tidytable_no_dot") %||% FALSE
  if (dot_option == TRUE) {
    dot_fns <- paste0(dotless_fns, ".")
    dot_fns <- lapply(dot_fns, get, envir = tidytable_ns)
    names(dot_fns) <- dotless_fns
    env_bind(tidytable_ns, !!!dot_fns)
    namespaceExport(tidytable_ns, dotless_fns)
  }
}

dotless_fns <- c(
  "across",
  "add_count",
  "arrange",
  "between",
  "bind_cols",
  "bind_rows",
  "c_across",
  "case",
  "case_when",
  "coalesce",
  "complete",
  "count",
  "crossing",
  "cur_group_id",
  "cur_group_rows",
  "desc",
  "distinct",
  "drop_na",
  "enframe",
  "expand",
  "expand_grid",
  "extract",
  "fill",
  "filter",
  "first",
  "last",
  "nth",
  "fread",
  "fwrite",
  "get_dummies",
  "group_split",
  "if_all",
  "if_any",
  "ifelse",
  "left_join",
  "right_join",
  "full_join",
  "inner_join",
  "anti_join",
  "semi_join",
  "lags",
  "leads",
  "map",
  "map_lgl",
  "map_int",
  "map_dbl",
  "map_chr",
  "map_dfc",
  "map_dfr",
  "map_df",
  "map2",
  "map2_lgl",
  "map2_int",
  "map2_dbl",
  "map2_chr",
  "map2_dfc",
  "map2_dfr",
  "map2_df",
  "mutate",
  "mutate_rowwise",
  "n",
  "n_distinct",
  "nest",
  "nest_by",
  "pivot_longer",
  "pivot_wider",
  "pull",
  "relocate",
  "rename",
  "rename_with",
  "replace_na",
  "row_number",
  "select",
  "separate",
  "separate_rows",
  "slice",
  "summarise",
  "summarize",
  "top_n",
  "transmute",
  "uncount",
  "unite",
  "unnest",
  "unnest_longer",
  "unnest_wider",
  "walk"
)
